import type { AnalysisResult, TaskId } from "./types";
import { ALL_TASKS } from "./types";

export function resultToMarkdown(
  result: AnalysisResult,
  opts: { target: string; language: string; tasks: TaskId[]; durationMs?: number }
): string {
  const lines: string[] = [
    `# Code Lens Analysis`,
    ``,
    `- **Target:** \`${opts.target}\``,
    `- **Language:** ${opts.language}`,
    `- **Tasks:** ${opts.tasks.map((t) => ALL_TASKS.find((x) => x.id === t)?.label ?? t).join(", ")}`,
  ];
  if (opts.durationMs != null) {
    lines.push(`- **Duration:** ${(opts.durationMs / 1000).toFixed(1)}s`);
  }
  lines.push(``, `---`, ``);

  if (result.explanation) {
    lines.push(`## Explain`, ``, result.explanation, ``);
  }
  if (result.bug_fixes) {
    lines.push(`## Fix Bugs`, ``);
    if (result.bug_fixes.summary) lines.push(result.bug_fixes.summary, ``);
    if (result.bug_fixes.issues?.length) {
      for (const issue of result.bug_fixes.issues) {
        lines.push(`- ${issue}`);
      }
      lines.push(``);
    }
    if (result.bug_fixes.fixed_code) {
      lines.push("```" + opts.language, result.bug_fixes.fixed_code, "```", ``);
    }
  }
  if (result.tests) {
    lines.push(`## Generate Tests`, ``, `Framework: **${result.tests.framework}**`, ``);
    if (result.tests.code) {
      lines.push("```" + opts.language, result.tests.code, "```", ``);
    }
  }
  if (result.improvements?.length) {
    lines.push(`## Suggest Improvements`, ``);
    result.improvements.forEach((item, i) => {
      lines.push(`${i + 1}. ${item}`);
    });
    lines.push(``);
  }

  lines.push(`---`, `_Generated by Code Lens · grok-4.5_`);
  return lines.join("\n");
}

export function downloadText(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
