import type { AnalysisResult, Finding, TaskId } from "./types";
import { ALL_TASKS } from "./types";
import { collectAllFindings, sortBySeverity } from "./findings";

function findingLine(f: Finding): string {
  const bits = [
    `**[${f.severity}]** ${f.title}`,
    f.line != null ? `L${f.line}${f.endLine && f.endLine !== f.line ? `–${f.endLine}` : ""}` : null,
    f.ruleId ? `\`${f.ruleId}\`` : null,
    f.category ? `_${f.category}_` : null,
  ].filter(Boolean);
  let line = `- ${bits.join(" · ")}`;
  if (f.detail && f.detail !== f.title) line += `\n  ${f.detail}`;
  if (f.suggestion) line += `\n  → ${f.suggestion}`;
  return line;
}

export function resultToMarkdown(
  result: AnalysisResult,
  opts: {
    target: string;
    language: string;
    tasks: TaskId[];
    durationMs?: number;
    depth?: string;
  }
): string {
  const lines: string[] = [
    `# Code Lens Analysis`,
    ``,
    `- **Target:** \`${opts.target}\``,
    `- **Language:** ${opts.language}`,
    `- **Tasks:** ${opts.tasks.map((t) => ALL_TASKS.find((x) => x.id === t)?.label ?? t).join(", ")}`,
  ];
  if (opts.depth) {
    lines.push(`- **Depth:** ${opts.depth}`);
  }
  if (opts.durationMs != null) {
    lines.push(`- **Duration:** ${(opts.durationMs / 1000).toFixed(1)}s`);
  }
  lines.push(``, `---`, ``);

  if (result.quality) {
    lines.push(`## Quality spectrum`, ``);
    const q = result.quality;
    for (const [k, v] of Object.entries(q)) {
      if (typeof v === "number") lines.push(`- **${k}:** ${v}`);
    }
    lines.push(``);
  }

  if (result.explanation) {
    lines.push(`## Explain`, ``, result.explanation, ``);
  }
  if (result.bug_fixes) {
    lines.push(`## Fix Bugs`, ``);
    if (result.bug_fixes.summary) lines.push(result.bug_fixes.summary, ``);
    const structured = result.bug_fixes.structured_issues;
    if (structured?.length) {
      for (const f of sortBySeverity(structured)) {
        lines.push(findingLine(f));
      }
      lines.push(``);
    } else if (result.bug_fixes.issues?.length) {
      for (const issue of result.bug_fixes.issues) {
        lines.push(`- ${issue}`);
      }
      lines.push(``);
    }
    if (result.bug_fixes.fixed_code) {
      lines.push("```" + opts.language, result.bug_fixes.fixed_code, "```", ``);
    }
  }
  if (result.tests) {
    lines.push(`## Generate Tests`, ``, `Framework: **${result.tests.framework}**`, ``);
    if (result.tests.coverage_notes?.length) {
      lines.push(`Coverage:`, ``);
      for (const n of result.tests.coverage_notes) lines.push(`- ${n}`);
      lines.push(``);
    }
    if (result.tests.code) {
      lines.push("```" + opts.language, result.tests.code, "```", ``);
    }
  }
  if (result.improvements?.length) {
    lines.push(`## Suggest Improvements`, ``);
    result.improvements.forEach((item, i) => {
      lines.push(`${i + 1}. ${item}`);
    });
    lines.push(``);
  }
  if (result.security) {
    lines.push(
      `## Security Audit`,
      ``,
      `Risk level: **${result.security.risk_level}**`,
      ``
    );
    if (result.security.summary) lines.push(result.security.summary, ``);
    for (const f of sortBySeverity(result.security.findings)) {
      lines.push(findingLine(f));
    }
    lines.push(``);
  }
  if (result.architecture) {
    const a = result.architecture;
    lines.push(
      `## Architecture`,
      ``,
      `- **Coupling:** ${a.coupling}`,
      `- **Cohesion:** ${a.cohesion}`,
      ``
    );
    if (a.summary) lines.push(a.summary, ``);
    if (a.hotspots?.length) {
      lines.push(`### Hotspots`, ``);
      for (const f of sortBySeverity(a.hotspots)) {
        lines.push(findingLine(f));
      }
      lines.push(``);
    }
    if (a.recommendations?.length) {
      lines.push(`### Recommendations`, ``);
      a.recommendations.forEach((r, i) => lines.push(`${i + 1}. ${r}`));
      lines.push(``);
    }
  }

  const all = collectAllFindings(result);
  if (all.length) {
    lines.push(
      `---`,
      ``,
      `_Findings with line targets: ${all.filter((f) => f.line != null).length}/${all.length}_`,
      ``
    );
  }

  lines.push(`---`, `_Generated by Code Lens · grok-4.5_`);
  return lines.join("\n");
}

export function downloadText(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
