/**
 * Prism theme tuned for Glass Sapphire (indigo night + sapphire accent).
 * Based on oneDark structure; values chosen for contrast on --code-bg.
 */

import type { CSSProperties } from "react";

type PrismTheme = { [key: string]: CSSProperties };

export const sapphirePrism: PrismTheme = {
  'code[class*="language-"]': {
    color: "#d6e2f5",
    background: "none",
    fontFamily: 'var(--font-plex-mono), ui-monospace, monospace',
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    wordWrap: "normal",
    lineHeight: "1.5",
    tabSize: 2,
    hyphens: "none",
  },
  'pre[class*="language-"]': {
    color: "#d6e2f5",
    background: "transparent",
    fontFamily: 'var(--font-plex-mono), ui-monospace, monospace',
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    wordWrap: "normal",
    lineHeight: "1.5",
    tabSize: 2,
    hyphens: "none",
    padding: "1em",
    margin: "0",
    overflow: "auto",
  },
  comment: { color: "#5c6f8c", fontStyle: "italic" },
  prolog: { color: "#5c6f8c" },
  doctype: { color: "#5c6f8c" },
  cdata: { color: "#5c6f8c" },
  punctuation: { color: "#8ba0bf" },
  namespace: { opacity: 0.75 },
  property: { color: "#7eb6ff" },
  tag: { color: "#7eb6ff" },
  boolean: { color: "#c4a5ff" },
  number: { color: "#c4a5ff" },
  constant: { color: "#c4a5ff" },
  symbol: { color: "#c4a5ff" },
  deleted: { color: "#ff6b8a" },
  selector: { color: "#5eead4" },
  "attr-name": { color: "#5eead4" },
  string: { color: "#9ddea8" },
  char: { color: "#9ddea8" },
  builtin: { color: "#5eead4" },
  inserted: { color: "#5eead4" },
  operator: { color: "#89b8ff" },
  entity: { color: "#89b8ff", cursor: "help" },
  url: { color: "#89b8ff" },
  ".language-css .token.string": { color: "#9ddea8" },
  ".style .token.string": { color: "#9ddea8" },
  atrule: { color: "#f5c15a" },
  "attr-value": { color: "#f5c15a" },
  keyword: { color: "#9db8ff" },
  function: { color: "#6ec8ff" },
  "class-name": { color: "#f0c36a" },
  regex: { color: "#ff9eb5" },
  important: { color: "#ff9eb5", fontWeight: "bold" },
  variable: { color: "#ff9eb5" },
  bold: { fontWeight: "bold" },
  italic: { fontStyle: "italic" },
};
